services:
  mysql-test:
    image: mysql:8.4
    command: --default-authentication-plugin=mysql_native_password
    tmpfs:
      - /var/lib/mysql # en RAM
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: testbench
    ports:
      - 3307:3306