<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreatePaymentTypesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('fin_payment_types', function (Blueprint $table) {
            // NOT AUTOGENERATED
            $table->unsignedBigInteger('id')->primary();

            $table->string('name');
            $table->string('payment_gateway')->nullable();
            $table->tinyInteger('is_active')->nullable()->default(1);

            addedModifiedByColumns($table);
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('fin_payment_types');
    }
}
