<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateAccountsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {        
        Schema::create('fin_gl_accounts', function (Blueprint $table) {
            addMetaData($table);

            $table->string('account_segments_descriptor', 50)->nullable()->index(); // This will be autogenerated
            $table->string('account_description', 255);

            $table->tinyInteger('account_type')->nullable();
            
            // Account management flags
            $table->boolean('is_active')->default(true);
            $table->boolean('allow_manual_entry')->default(true);
            
            // Indexes for performance
            $table->index(['is_active', 'allow_manual_entry']);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('fin_gl_accounts');
    }
}
