<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateInvoiceTypesTable extends Migration
{
    /**
     * Run the migrations.
     */
    public function up()
    {
        Schema::create('fin_invoice_types', function (Blueprint $table) {
            // NOT AUTOGENERATED
            $table->unsignedBigInteger('id')->primary();

            $table->string('name');
            $table->string('prefix');

            // The sign multiplier is used to determine the sign of the invoice number. negative or positive
            $table->tinyInteger('sign_multiplier')->default(1);
            $table->unsignedBigInteger('next_number')->default(1);

            addedModifiedByColumns($table);
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down()
    {
        Schema::dropIfExists('fin_invoice_types');
    }
}
