<?php

namespace Condoedge\Finance\Models\Payable;

use Condoedge\Utils\Models\Model;

/**
 * @TRIGGERED BY: tr_historical_vendors_after_insert (insert_historical_vendors_v0001.sql)
 * 
 * This model is intended for read-only historical vendor data queries.
 * Records are automatically generated by database triggers each time a bill is created,
 * preserving the state of the vendor at that specific moment.
 * 
 * WARNING: Do not create or update these records manually as they are managed by database triggers.
 * We use triggers to avoid deleting or updating records in this table.
 */
class HistoricalVendor extends Model
{
    protected $table = 'fin_historical_vendors';

    /* RELATIONSHIPS */
    public function vendor()
    {
        return $this->belongsTo(Vendor::class, 'vendor_id');
    }

    public function bills()
    {
        return $this->hasMany(Bill::class, 'historical_vendor_id');
    }
}
