<?php

namespace Condoedge\Finance\Models;

use Condoedge\Utils\Models\Model;

/**
 * @TRIGGERED BY: tr_historical_customers_after_insert (insert_historical_customers_v0001.sql)
 * 
 * This model is intended for read-only historical customer data queries.
 * Records are automatically generated by database triggers each time an invoice is created,
 * preserving the state of the customer at that specific moment.
 * 
 * WARNING: Do not create or update these records manually as they are managed by database triggers.
 * We use triggers to avoid deleting or updating records in this table.
 */
class HistoricalCustomer extends Model
{
    protected $table = 'fin_historical_customers';

    /* RELATIONSHIPS */
    public function customer()
    {
        return $this->belongsTo(Customer::class, 'customer_id');
    }

    public function invoices()
    {
        return $this->hasMany(Invoice::class, 'historical_customer_id');
    }
}