<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateBillsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('fin_bills', function (Blueprint $table) {
            addMetaData($table);

            $table->foreignId('bill_type_id')->constrained('fin_bill_types');
            $table->bigInteger('bill_number')->unique(); // Auto-generated by trigger
            $table->string('bill_reference')->nullable(); // Calculated field
            
            // Calculated amounts
            $table->decimal('bill_amount_before_taxes', 19, config('kompo-finance.decimal-scale'))->default(0);
            $table->decimal('bill_total_amount', 19, config('kompo-finance.decimal-scale'))->storedAs('bill_amount_before_taxes + bill_tax_amount');
            $table->decimal('bill_due_amount', 19, config('kompo-finance.decimal-scale'))->default(0);
            $table->decimal('bill_tax_amount', 19, config('kompo-finance.decimal-scale'))->default(0);
            
            $table->foreignId('bill_status_id')->constrained('fin_bill_statuses');
            
            // Dates
            $table->date('bill_date');
            $table->date('bill_due_date');
            
            // Payment and approval
            $table->integer('payment_type_id');
            $table->boolean('is_draft')->default(true);
            $table->foreignId('approved_by')->nullable()->constrained('users');
            $table->timestamp('approved_at')->nullable();
            
            // Vendor relationships
            $table->foreignId('historical_vendor_id')->constrained('fin_historical_vendors');
            $table->foreignId('vendor_id')->constrained('fin_vendors');
            
            // Accounts
            $table->foreignId('account_payable_id')->nullable()->constrained('fin_accounts');
            
            $table->index(['bill_date']);
            $table->index(['bill_due_date']);
            $table->index(['vendor_id']);
            $table->index(['bill_status_id']);
            $table->index(['is_draft']);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('fin_bills');
    }
}
